### ISSUE TITLE
Can you give a sample code for extracting the master key from unencrypted bitcoin core wallet 

### ISSUE THREAD

**Issue by shreyapz** [akx/walletool#2]
Can you give a sample code for extracting the master key from unencrypted bitcoin core wallet

**Comment by akx** [comment]
If you can give me such a file, then maybe.

**Comment by shreyapz** [comment]
Sure I will. I would also like to know that these private keys which I have extracted by executing your code are in which format?
As I got a huge list of addresses and their private keys(which starts from 5xxxx.....) as an output for your program.
I tried to confirm if these private keys are correct or not by going into the console window of btcore. 
by giving command dumpprivatekeys 'one_of_the_address_extracted_from_your_prog' and I got a different private key for that particular address. 
P.S - my wallet is default wallet. I did not encrypt with the passphrase and tried to run the code on this unencrypted wallet.dat file. 

Really appreciate your help :)

**Comment by akx** [comment]
It's been a while since I've touched the code, but according to [these bits](https://github.com/akx/walletool/blob/bb2629acb04a5ef5b1aa741c0f78c14455d34132/walletool/wallet_items.py#L174-L177), which might be equivalent to https://en.bitcoin.it/wiki/Wallet_import_format but I'll have to check. You can edit that code to dump things in raw hex and then maybe use something like http://gobittest.appspot.com/PrivateKey to convert?

**Comment by shreyapz** [comment]
Getting this error while running wallet_items.py

C:\Python27\walletool>python wallet_items.py
Traceback (most recent call last):
  File "wallet_items.py", line 5, in <module>
    from walletool.bc_data_stream import BCDataStream
ModuleNotFoundError: No module named 'walletool'

**Comment by akx** [comment]
You aren't supposed to run the modules within the `walletool` package as scripts.

**Comment by shreyapz** [comment]
Thanks for the help :) @akx
